language: android
android:
  components:
    - android-28
    - build-tools-28.0.3

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"

script:
  - ./gradlew clean assembleDebug assembleRelease testDebug
  # Codecov.io
  - bash <(curl -s https://codecov.io/bash)