language: android
android:
  components:
    - android-28
    - build-tools-28.0.3

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"

script:
  - ./gradlew clean assembleDebug assembleRelease testDebug
  # Renaming folder and files of reports so codecov.io can find it
  - mv app/build/reports/jacoco/createDebugUnitTestCoverageReport app/build/reports/jacoco/jacocoTestDebugUnitTestReport
  - mv app/build/reports/jacoco/jacocoTestDebugUnitTestReport/createDebugUnitTestCoverageReport.xml app/build/reports/jacoco/jacocoTestDebugUnitTestReport/jacocoTestDebugUnitTestReport.xml
  # Codecov.io
  - bash <(curl -s https://codecov.io/bash)